feat/boilerplate_enhancements
contentstack/marketplace-app-boilerplate pull request #16
Opened 2022-11-25 10:20 UTC by almeida-shrutika

Changes:
- Default route needs a new UX when npm start command opens stack-dashboard route
  On this route educate the user, that they need to go back to their stack dashboard to experience the app their

- Remove Venus library as a bundled dependency

- App URL issue if extra / is present

- Config data is not loading correctly. (Remove dependency)

- Remove async from useEffect from MarketplaceProvider

2022-11-25 10:27 UTC, surajcontentstack requested changes
@almeida-shrutika we need one more change in installationData hook. Ask Amit about the change

2022-11-25 10:27 UTC, surajcontentstack commented on src/MarketplaceAppProvider.tsx
> +      });
add a catch here for promise. It will never go into catch block. ?You can get rid of try catch

2022-11-25 11:08 UTC, surajcontentstack approved these changes
@almeida-shrutika test useInstallationData hook properly

2022-11-28 08:08 UTC, Amitkanswal approved these changes

2022-11-29 06:33 UTC, merged