Feat/boilerplate enhancements
contentstack/marketplace-app-boilerplate pull request #27
Opened 2023-01-18 06:21 UTC by almeida-shrutika

Changes:
- Update App title
- Add locales files for rte labels
- Remove 0 properties from rte css file
- Remove @emotion/core package from rte
- Update the folder structure for /src folder
- Add locales fils for the text labels
- Add an example data.json file for playwright tests
- Replace jotai library with context API

2023-01-18 07:34 UTC, surajcontentstack requested changes

2023-01-20 07:06 UTC, surajcontentstack requested changes

2023-01-20 07:06 UTC, surajcontentstack commented on src/common/hooks/useAppSdk.tsx
> +  const { appSdk } = useContext(MarketplaceContext) as MarketplaceContextType;
REname context to "MarketplaceAppContext

2023-01-20 07:06 UTC, surajcontentstack commented on src/common/hooks/useInstallationData.tsx
> +  const { installationData, loading } = useContext(
setter function is missing

2023-01-23 06:50 UTC, surajcontentstack requested changes

2023-01-23 06:50 UTC, surajcontentstack commented on src/containers/CustomField/CustomField.test.tsx
> +  //   await waitFor(() => {
Need test cases

2023-01-23 06:50 UTC, surajcontentstack commented on src/setupTests.ts
> +// jest.mock("mixpanel-browser");
Remove all commented code

2023-01-24 13:35 UTC, surajcontentstack requested changes

2023-01-25 12:20 UTC, surajcontentstack approved these changes
Looks good to me

2023-01-25 12:21 UTC, abhishek305 approved these changes

2023-02-01 05:53 UTC, merged