ECO-3470-Implemented-Asset-Sidebar-Screen
contentstack/marketplace-app-boilerplate pull request #63
Opened 2023-08-03 14:02 UTC by Contentstack-AnkitaD

- Implemented the UI for Asset Sidebar Location:
<img width="1728" alt="image" src="https://github.com/contentstack/marketplace-app-boilerplate/assets/115449840/d6d921b6-fa44-481a-8fa0-b64ef0f372b3">

2023-08-03 14:23 UTC, MaitriGurey1 approved these changes

2023-08-03 15:41 UTC, abhishek305 requested changes

2023-08-03 15:41 UTC, abhishek305 commented on src/containers/AssetSidebarWidget/AssetSidebar.tsx
> +//TODO:  need to update the RC modal
do we need these comments? If not remove this

2023-08-03 15:41 UTC, abhishek305 commented on src/containers/AssetSidebarWidget/AssetSidebar.tsx
> +  const [isRawConfigModalOpen, setRawConfigModalOpen] = useState(false);
add proper type for this state

2023-08-03 15:41 UTC, abhishek305 commented on src/containers/AssetSidebarWidget/AssetSidebar.tsx
> +  };
wrap this in useCallback

2023-08-03 15:41 UTC, abhishek305 commented on src/containers/index.css
> +  /* font-size: 0.875rem; */
remove comment

2023-08-04 05:59 UTC, Amitkanswal approved these changes

2023-08-04 05:59 UTC, abhishek305 approved these changes

2023-08-04 05:59 UTC, merged